### ISSUE TITLE
[BUG] ERROR: Exception in runner thread

### ISSUE THREAD

**Issue by tmnhy** [aristocratos/btop#9] opened 2021-09-20 12:33 UTC
**Describe the bug**

```
ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068066) >= _Nm (which is 101)
```

**To Reproduce**

Run `btop` and wait

**Expected behavior**

Handling an exception with code

**Screenshots**

**Info (please complete the following information):**
 - btop++ version: btop version: 1.0.1
 - Architecture: [x86_64, aarch64, etc.] x86_64
 - Platform: Linux
 - (Linux) Kernel: 5.14.1
 - (OSX/FreeBSD) Os release version:
 - Terminal used: Konsole
 - Font used: terminus

**Additional context**

contents of `~/.config/btop/error.log`:  empty

contents of `~/.config/btop/btop.log`:
```
2021/09/20 (11:20:41) | ===> btop++ v.1.0.1
2021/09/20 (11:20:41) | ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068063) >= _Nm (which is 101)

2021/09/20 (11:39:42) | ===> btop++ v.1.0.1
2021/09/20 (11:39:42) | ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068063) >= _Nm (which is 101)

2021/09/20 (12:29:13) | ===> btop++ v.1.0.1
2021/09/20 (12:29:13) | ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068066) >= _Nm (which is 101)

2021/09/20 (15:19:59) | ===> btop++ v.1.0.1
2021/09/20 (15:19:59) | ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068066) >= _Nm (which is 101)

2021/09/20 (15:32:25) | ===> btop++ v.1.0.1
2021/09/20 (15:32:25) | DEBUG: Starting in DEBUG mode!
2021/09/20 (15:32:25) | INFO: Logger set to DEBUG
2021/09/20 (15:32:25) | DEBUG: Setting LC_ALL=ru_RU.utf8
2021/09/20 (15:32:25) | INFO: Running on /dev/pts/4
2021/09/20 (17:36:35) | ERROR: Exception in runner thread -> Proc:: -> array::at: __n (which is 18446744071562068068) >= _Nm (which is 101)
2021/09/20 (17:36:35) | INFO: Quitting! Runtime: 02:04:10
```

**Comment by aristocratos** [comment] 2021-09-20 15:02
@tmnhy 
> Expected behavior
>Handling an exception with code

This exception was handled by code, by showing where the exception happened and what happened and then exiting. No handling would mean no message and a segmentation fault.

Need some more information however:
Does this happen randomly or when you do a specific action? 
Do you have the options for `proc` set to default and if not, what values are set?

**Comment by aristocratos** [comment] 2021-09-20 16:35
@tmnhy 
This should be fixed in [release 1.0.2](https://github.com/aristocratos/btop/releases/tag/v1.0.2)

But the root cause of your issue looks like a underflow of a unsigned long long, and I'm not quite sure where or why it's happening. But it shouldn't crash in latest release after clamping the value to the size of the array it's accessing.

**Comment by tmnhy** [comment] 2021-09-20 16:56
Thx I'll be watching

**Comment by nulopes** [comment] 2021-09-21 13:36
Hi, this has happened to me with version 1.0.2 just now. One of the times I wasn't in front of the computer, the other time I launched and it crashed with that error in a few seconds.
I haven't changed any settings and the percentages seem right (at least when I'm watching)

If I can do anything more to help, please tell me and I'll do it.

**Comment by tmnhy** [comment] 2021-09-21 14:15
1.0.2 did not solve the problem

**Comment by aristocratos** [comment] 2021-09-21 15:33
@tmnhy @nulopes
Pushed some possible fixes in latest [commit](https://github.com/aristocratos/btop/commit/8d3e4575be9e846ddb550bbabade4b78347df2ec) that you can try. If you need the precompiled static binaries, you're gonna have to wait a bit.

**Comment by aristocratos** [comment] 2021-09-21 18:07
@tmnhy 
Are all the memory values off or is some correct?

Could you post the output from some of the wrong ones with: `cat /proc/<pid>/stat`

**Comment by tmnhy** [comment] 2021-09-21 18:17
Now only firefox.

E.g.:
* btop - 9T
* bpytop - 165M
* htop - RES - 165M

`/proc/{pid}/stat`:
```
27129 (Isolated Web Co) S 10909 10731 10731 0 -1 4210944 18364 0 51 0 118 21 0 0 20 0 29 0 2959205 2657251328 42370 18446744073709551615 94695736011472 94695736682384 140726568493696 0 0 0 0 69634 1082133752 0 0 0 17 14 0 0 0 0 0 94695736695120 94695736696376 94695766564864 140726568501365 140726568501558 140726568501558 140726568505311 0
```

**Comment by aristocratos** [comment] 2021-09-21 18:42
@tmnhy 
Wow, your stat file is reporting `18446744073709551615` RSS in pages (field 24). That is then in turn multiplied by your page size, usually `4096` (bytes) which overflows the variable and comes back around from 0 to the value you get.

What values do you get from
`cat /proc/<pid>/statm` and `cat /proc/<pid>/status` for the same PID.

**Comment by aristocratos** [comment] 2021-09-21 19:29
@tmnhy 
There, fixed in [v1.0.4](https://github.com/aristocratos/btop/releases/tag/v1.0.4)
Memory collection will now fallback to using /proc/<pid>/statm if values from /proc/<pid>/stat looks wrong.

**Comment by tmnhy** [comment] 2021-09-21 19:34
thx great

**Comment by kkremitzki** [comment] 2021-09-21 22:22
This was happening to me consistently earlier after a little less than an hour of runtime, but it seems to be fixed now, thanks.

**Closed** 2021-09-23 05:38 UTC
Labels: bug

**Comment by ghomem** [comment] 2024-07-19 14:12
Semi on-topic question: what is the metric that btop uses for the memory of a process? RSS? PSS? Something custom?

(I am asking because the topic of memory metrics is confusing and different software tracks different things)
