### ISSUE TITLE
[BUG] crash on MacOS Monterey arm64

### ISSUE THREAD

**Issue by tidux** [aristocratos/btop#280] opened 2022-02-28 15:07 UTC
btop crashes at start with the following error:

`ERROR: Exception in runner thread -> Proc:: -> wstring_convert::from_bytes`

This occurs both with the static release binary and the Homebrew package.

**Comment by aristocratos** [comment] 2022-03-04 19:18
@tidux
Duplicate of #277

It should be fixed in latest commits, will push a new release when confirmed fixed.

**Closed by aristocratos** 2022-03-04 19:18 UTC
Labels: bug
