### ISSUE TITLE
[BUG] Config file is written even when no changes are made

### ISSUE THREAD

**Issue by Kernald** [aristocratos/btop#444] opened 2022-10-11 05:59 UTC
**Describe the bug**
Starting btop and quitting without making any changes still results in the config file being overwritten. When using tools like [chezmoi](https://www.chezmoi.io/) to share the configuration file between different machines, it's problematic - btop's version number is written at the top of the file (and not every distribution/OS is equal in terms of update speed - my Linux machine has btop 1.2.12 but my macOS laptop only has 1.2.9), for example - so the file changes just by starting btop.

**To Reproduce**
Change the configuration file manually, start and quit btop, notice the configuration file has been overwritten.

**Expected behavior**
The configuration file shouldn't be overwritten if no changes were made from the UI

**Screenshots**
N/A

**Info (please complete the following information):**
 - btop++ version: `1.2.12` and `1.2.9`
 - Binary: from Archlinux packages and homebrew on macOS
 - Architecture: [x86_64, aarch64, etc.] `x86_64` and `arm64`
 - Platform: [Linux, FreeBSD, OsX] Linux and macOS
 - (Linux) Kernel: `5.19.13-arch1-1`
 - (OSX/FreeBSD) Os release version: 12.6
 - Terminal used: gnome-terminal, iTerm2
 - Font used:

**Additional context**

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by aristocratos** [comment] 2022-10-13 10:49
@Kernald 
> btop++ version: 1.2.12 and 1.2.9

Not a bug.
Expected behavior is not that the config file is gonna be compatible between all versions of btop.
Config options format change, are added and removed. Therefor the config file is rewritten so it can be externally edited with the correct options for the version you are running.

The solution is to make sure you running the same version on all your systems if you want to share the config file.
The config is also only written when exiting the program, so only the _last_ closed instance of btop will have it settings saved.

**Closed** 2022-10-23 18:01 UTC
