### ISSUE TITLE
[BUG] Erroneous size calculations on 32-bit Linux

### ISSUE THREAD

**Issue by Serentty** [aristocratos/btop#132] opened 2021-11-02 16:49 UTC
**Describe the bug**

The sizes are all out of wack. These percentages make no sense. I suspect that there are some shenanigans going on with integer wrapping because either the APIs being used are not the unambiguously 64-bit ones but instead the “machine word sized” ones, or that BTOP++ is truncating the values to the size of a machine word. That’s all speculation on my part.

**To reproduce**

If it’s what I suspect, then just run BTOP++ on a 32-bit Linux system, regardless of architecture. I don’t get this issue on 64-bit PowerPC or 64-bit ARM. I haven’t run this on x86 before.

**Expected behavior**

Large (> 4 GiB) sizes are reported properly.

**Screenshots**

![PXL_20211102_163345619](https://user-images.githubusercontent.com/614548/139907795-87ae3549-94b6-4b62-b07b-828d9921bedd.jpg)

**Info (please complete the following information):**

 - BTOP++ version: 1.0.20
 - Binary: Self-compiled
 - (If compiled) Compiler and version: GCC 10.2.1
 - Architecture: [x86_64, aarch64, etc.]: `powerpc` (this means 32-bit PowerPC)
 - Platform: Linux
 - (Linux) Kernel: 5.13.19_1
 - Terminal used: TTY
 - Font used: Whatever the default is

**Comment by aristocratos** [comment] 2021-11-03 15:44
@Serentty 
I thought this was only happening when running the 32-bit binaries on 64-bit hardware, guess the issue is deeper than that then.

Probably need to put in some preprocessor conditionals for 32-bit to swap some of the kernel functions.
Will take a look at it when I've got time.

**Comment by Serentty** [comment] 2021-11-03 18:57
Thanks! Yeah, this is running on a PowerPC G4 (7400), which is a 32-bit chip.

**Comment by aristocratos** [comment] 2021-11-03 20:08
@Serentty 
Should be fixed in latest commit.
Pull and rebuild or download [btop-powerpc-linux-musl](https://github.com/aristocratos/btop/suites/4248648954/artifacts/110222238) from the continuous builds to test.

**Comment by Serentty** [comment] 2021-11-03 20:19
I’m using GLIBC, so I‘ll rebuild.

**Comment by aristocratos** [comment] 2021-11-03 20:21
@Serentty 
> I’m using GLIBC, so I‘ll rebuild.

It's statically built, so doesn't matter what system clib you have, everything needed is built in to the binary.

**Comment by Serentty** [comment] 2021-11-03 20:44
Welp, I already compiled it anyway. It seems to have fixed things on my end.

**Comment by aristocratos** [comment] 2021-11-03 21:14
Fixed in [v1.0.22](https://github.com/aristocratos/btop/releases/tag/v1.0.22)

**Closed by aristocratos** 2021-11-03 21:14 UTC
Labels: bug

**Comment by Serentty** [comment] 2021-11-03 22:33
Nice, thanks.
