### ISSUE TITLE
[BUG] memB unit showing as "G" instead of "M"

### ISSUE THREAD

**Issue by Motodavide** [aristocratos/btop#307] opened 2022-04-08 18:28 UTC
**Describe the bug**

`memB` values are shown with a `G` when the right unit is clearly `M`, both in decimal
units and in non-decimal.

**To Reproduce**

Just start btop.

**Expected behavior**

`btop` should display the right unit.

**Screenshot**

![2022_04_ 8](https://user-images.githubusercontent.com/78605310/162500396-f9f3d51a-327b-47ec-be06-1036018ba104.png)

**Info (please complete the following information):**
 - btop++ version: `1.2.5`
 - Binary: static binary from release
 - (If compiled) Compiler and version:
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: `5.17.1-zen`
 - (OSX/FreeBSD) Os release version:
 - Terminal used: `alacritty`
 - Font used:

**Comment by aristocratos** [comment] 2022-04-13 09:06
@Motodavide 
Duplicate of #283
It's fixed in latest commits.

**Comment by aristocratos** [comment] 2022-04-13 09:21
Fixed in [v1.2.6](https://github.com/aristocratos/btop/releases/tag/v1.2.6)

**Closed** 2022-04-26 20:00 UTC
Labels: bug
