### ISSUE TITLE
[BUG] '-fcf-protection' is being enabled for i586 builds

### ISSUE THREAD

**Issue by sbradnick** [aristocratos/btop#106] opened 2021-10-19 17:54 UTC
**Describe the bug**

I'm having issues w/ the i586 [auto]builds as a result of `-fcf-protection` being added --

```
[   23s] PLATFORM   ?| Linux
[   23s] ARCH       ?| i586
[   23s] CXX        ?| g++ (11.2.1)
[   23s] THREADS    :| 4
[   23s] REQFLAGS   !| -std=c++20
[   23s] WARNFLAGS  :| -Wall -Wextra -pedantic
[   23s] OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=4
[   23s] LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
[   23s] CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
[   23s] LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
[   23s] 
[   23s] Building btop++ (v1.0.18) Linux i586
[   23s] Compiling src/btop.cpp
[   23s] cc1plus: error: '-fcf-protection' is not compatible with this target
[   23s] make: *** [Makefile:189: obj/btop.o] Error 1
[   23s] make: *** Waiting for unfinished jobs....
[   23s] Compiling src/btop_config.cpp
[   23s] cc1plus: error: '-fcf-protection' is not compatible with this target
[   23s] make: *** [Makefile:189: obj/btop_config.o] Error 1
[   23s] Compiling src/btop_draw.cpp
[   23s] cc1plus: error: '-fcf-protection' is not compatible with this target
[   23s] make: *** [Makefile:189: obj/btop_draw.o] Error 1
[   23s] Compiling src/btop_input.cpp
[   23s] cc1plus: error: '-fcf-protection' is not compatible with this target
[   23s] make: *** [Makefile:189: obj/btop_input.o] Error 1
[   23s] error: Bad exit status from /var/tmp/rpm-tmp.Ukc8N8 (%build)
[   23s] 
[   23s] 
[   23s] RPM build errors:
[   23s]     Bad exit status from /var/tmp/rpm-tmp.Ukc8N8 (%build)
```

If I take `i%86` out of line #27 in Makefile, it builds successfully as well as a x86_64 build using it correctly:

`fneq ($(filter x86_64, $(ARCH)),)`

**To Reproduce**

Standard build procedure produces this issue.

**Expected behavior**

An i586 build to complete successfully (as it was prior).

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: 1.0.18
 - Binary: building in https://build.opensuse.org
 - Compiler and version: g++ (SUSE Linux) 11.2.1 20210816 [revision 056e324ce46a7924b5cf10f61010cf9dd2ca10e9]
 - Architecture: [x86_64, aarch64, etc.] i586
 - Platform: [Linux, FreeBSD, OsX]
 - (Linux) Kernel: 5.14.11-1-default
 - (OSX/FreeBSD) Os release version: n/a
 - Terminal used: kitty
 - Font used: CaskaydiaCove Nerd Font

**Additional context**

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run `gdb btop`

2. `r` to run, wait for crash and press enter

3. `thread apply all bt` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by aristocratos** [comment] 2021-10-19 18:51
@sbradnick 
Huh, is this just for i586 builds? Because looking at the [i486](https://github.com/aristocratos/btop/runs/3941257530?check_suite_focus=true) and [i686](https://github.com/aristocratos/btop/runs/3941257593?check_suite_focus=true) static builds they run fine.

**Comment by sbradnick** [comment] 2021-10-19 19:17
yes, these are the ARCH items the project builds against, with testing for Tumbleweed/Factory and Leap 15.3:

- aarch64
- armv7l
- i586
- ppc
- ppc64
- ppc64le
- riscv64
- s390x
- x86_64

I'd really not given it much thought as all of them would build successfully ~ until (maybe) yesterday when i586 started showing "failed" and that message.

**Comment by jan-guenter** [comment] 2021-10-21 00:11
Sorry it took me so long, but I did quite a bit of testing.

@sbradnick
I can confirm that I could replicate the build error using the i586 opneSUSE Tumbleweed docker image.
However in the same container I was able to build btop using the gcc10-g++ package installed through zypper.
Next I tried to find any other i*86 gcc11 toolchain and the only one I found is the i686 cross toolchain for Ubuntu impish. Using the official ubuntu:impish docker image (on x86_64) I installed the cross toolchain and it works as expected with `-fcf-protection`:
```
PLATFORM   ?| Linux
ARCH       ?| i686
CXX        ?| i686-linux-gnu-g++ (11.2.0)
THREADS    :| 16
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=16
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.18) Linux i686
Compiling src/btop_config.cpp
Compiling src/btop_tools.cpp
Compiling src/btop_draw.cpp
Compiling src/btop.cpp
Compiling src/btop_input.cpp
Compiling src/btop_theme.cpp
Compiling src/btop_menu.cpp
Compiling src/linux/btop_collect.cpp
-> obj/btop_theme.o                (1.4MiB) (05s)
-> obj/btop_config.o               (1.4MiB) (05s)
-> obj/btop_input.o                (1.4MiB) (05s)
-> obj/btop_tools.o                (1.3MiB) (05s)
-> obj/btop.o                      (1.8MiB) (06s)
-> obj/btop_menu.o                 (2.0MiB) (06s)
-> obj/btop_draw.o                 (2.2MiB) (07s)
-> obj/linux/btop_collect.o        (3.0MiB) (08s)

Linking and optimizing binary...
-> bin/btop                        (1.4MiB) (07s)
```

Somehow the suse gcc11 for i586 is built without cet support for some reason.
There is a configure flag in the gcc build scripts `--disable-cet` / `--enable-cet`.
According to the gcc build instructions this flag is `--enable-cet=auto`:
> --enable-cet=auto is default. CET is enabled on Linux/x86 if target binutils supports Intel CET instructions and disabled otherwise. In this case, the target libraries are configured to get additional -fcf-protection option.

I'm not terrible familiar with the suse packaging process, so I don't know exactly where to look for the build spec for the gcc build specs used to build the i586 gcc11.
@sbradnick Could you perhaps find the those specs or talk to the package maintainer. Take a look if cet is forcefully disabled and if not, try to find the configure log to see what the configure script detected for the cet setting.
Your help would be really appreciated.

@aristocratos Since cet support could be disabled for any platform depending on the gcc build it, perhaps would be prudent to build a compiler flag support detection into the Makefile. Simply executing $(CPP) with the flag under test using a dummy cpp file with empty main and check the $? error level returned. Or maybe reconsider using cmake, my version built just fine on suse using cmake simply not using the unsupported flag.

**Comment by aristocratos** [comment] 2021-10-21 06:23
@sbradnick @jan-guenter 

Added a oneliner in the Makefile that tests all compiler flags, with the added benefit of reducing conditionals.

https://github.com/aristocratos/btop/blob/a046f759497e6c05b3b9299b9f435cf219b50097/Makefile#L82

Will create a new release later today.

**Comment by jan-guenter** [comment] 2021-10-21 14:49
@sbradnick glad to here it's working for you!
> ```
> %if 0%{suse_version} >= 1500
> 	--enable-cet=auto \
> %else
> 	--disable-cet \
> %endif
> ```

This really doesn't explain to me why the i586 build failed on Tumbleweed since it should have cet support according to this.
Would you mind closing the issue if you don't have any further questions or problems relating to it?

@DimStar77
sorry for bothering you like this. I tagged you, since you are the package maintainer of gcc11 on openSUSE:Factory.
Would you mind skimming this issue? I don't really know enough about the subject to decide weather this is a bug in opensuses gcc11 build or expected behavior. However I'm always keen on learning and would be grateful for any kind of explanation.

**Comment by aristocratos** [comment] 2021-10-21 14:55
Fixed in [v1.0.19](https://github.com/aristocratos/btop/releases/tag/v1.0.19)

Closing

**Closed by aristocratos** 2021-10-21 14:55 UTC
Labels: bug

**Comment by DimStar77** [comment] 2021-10-21 15:20
Got some feedback:

> one needs a target CPU that supports CMOV
> it was added with Pentium Pro, so -march=i586 is not supported, while -march=i686 is

Which explains why the gcc11/i586 build does not support CET, but the tested i686 build in  https://github.com/aristocratos/btop/issues/106#issuecomment-948127415 did

**Comment by zv-io** [comment] 2021-10-21 17:14
I maintain `musl.cc`; thank you for the reports. I'll be sure to include a fix for this in the next release.
